version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://backend:8080
    container_name: parcial-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: bookstore  
    container_name: parcial-backend
    ports:
      - "8080:8080"
